apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-pod

  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongodb-pod
    spec:
      containers:
        - image: mongo:latest
          name: mongodb-container
          ports:
            - containerPort: 27017