apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb-database
  type: ClusterIP
  ports:
    - name: mongodb-port
      port: 27017
      targetPort: 27017
