apiVersion: v1
kind: Service
metadata:
  name: simple-app-service #! Host name
spec:
  selector:
    app: simple-backend-application
  type: LoadBalancer #! Important to mentions also in minikube 
  ports:
    - port: 4000
      # nodePort: 30008
      # protocol: TCP
