name: CI/CD pipeline for K8s Process
on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up QEMU
        uses: actions/setup-qemu-action@v3

      - name: Set up Build
        uses: actions/setup-buildx-action@v3

      - name: Install Dependencies
        run: |
          cd App
          npm install
          echo "All installation done!!! 🎊🎉"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and deploy
        uses: docker/build-push-action@v3
        with:
          context: ./App
          push: true
          tags: fradriks/node-app:latest
