name: CI/CD pipeline for K8s Process
on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          cd App
          npm install
      - run: echo "All done!🎉"
